# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_remove_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
