# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 18:09
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
